name: "test"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - uses: ./
    - run: |
         echo $BRANCH_NAME
         echo $BRANCH_NAME_LOWER_CASE
